// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vhagttufdirweivhgtlo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZoYWd0dHVmZGlyd2VpdmhndGxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNjYwNDcsImV4cCI6MjA3MDY0MjA0N30.0Ia4uzcWRc1mSw3Hmu9v1M5bXJmhvjIM8sI3iMmvgNc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});